# Generated by Django 3.0.6 on 2020-05-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200522_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrequests',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferRide'),
        ),
    ]
