# Generated by Django 3.0.6 on 2020-05-22 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20200522_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingrequests',
            unique_together={('request_id', 'request_from', 'request_to')},
        ),
    ]
