# Generated by Django 3.0.6 on 2020-05-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200522_2108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingrequests',
            unique_together=set(),
        ),
    ]
