# Generated by Django 3.0.6 on 2020-05-22 21:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_auto_20200522_2137'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='pendingrequests',
            index_together={('request_id', 'request_from', 'request_to')},
        ),
    ]
