# Generated by Django 3.0.6 on 2020-05-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200522_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingrequests',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='pendingrequests',
            index_together=set(),
        ),
    ]
